id = "one-dark-pro-plus"
name = "One Dark Pro Plus Theme"
version = "0.0.1"
schema_version = 1
description = "One Dark Pro Plus Theme for Zed"
repository = "https://github.com/ZorinFoss/zed-one-dark-pro-plus"
authors = ["ZorinFoss"]
themes = ["themes/one-dark-pro-plus.json"]
languages = []

[lib]

[grammars]

[language_servers]

[slash_commands]

[indexed_docs_providers]
